
default: &default
  MAIN: "Paley Library"
  AMBLER: "Ambler Campus Library"
  BLOCKSON: "Blockson Collection"
  CLAEDTECH: "CLA Ed Tech Library"
  GINSBURG: "Ginsburg Health Science Library"
  HARRISBURG: "Harrisburg Campus Library"
  JAPAN: "Japan Campus Library"
  KARDON: "Remote Storage"
  LAW: "Law Library"
  MEDIA: "Media Services"
  PODIATRY: "Krausz Library of Podiatric Medicine"
  PRESSER: "Presser Music Library"
  RES_SHARE: "Resource Sharing Library"
  ROME: "Rome Campus Library"
  SCRC: "Special Collections Research Center"
  EMPTY: "Other"

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
