default: &default
  AMBLER:
    aarc: Archives Collection
    imc: IMC
    intref: Internal Reference
    aleisure: Leisure Reading
    media: Media
    micro: Microform
    newbooks: New Books Shelf
    oversize: Oversize Stacks
    reference: Reference
    reserve: Reserves
    stacks: Stacks
    UNASSIGNED: Location information not available
  ASRS:
    ASRS: BookBot
    ASRS_TEST: ASRS_TEST
    media: BookBot
    reference: BookBot
    UNASSIGNED: Location information not available
  BLOCKSON:
    rarestacks: Reading Room
    UNASSIGNED: Location information not available
  CLAEDTECH:
    media: Media
    reserves: Reserves
    UNASSIGNED: Location information not available
  DSC:
    DSC: Equipment
    games: Games
    REF: Reference
    UNASSIGNED: Location information not available
  GINSBURG:
    circ: Circulation Collection
    intref: Internal Reference
    leisure: Leisure Reading
    medhum: Medical Humanities
    oversize: Oversize Stacks
    reference: Reference
    reserve: Reserves
    serials: Journals
    stacks: Stacks
    techserv: Technical Services
    UNASSIGNED: Location information not available
  HARRISBURG:
    harrisburg: Harrisburg Campus Library
    intref: Internal Reference
    media: Media
    oversize: Oversize Stacks
    reference: Reference
    reserve: Reserves
    stacks: Stacks
    UNASSIGNED: Location information not available
  JAPAN:
    media: Media
    osaka: Osaka Collection
    reference: Reference
    reserve: Reserves
    serials: Journals
    stacks: Stacks
    remote: Closed Stacks
    UNASSIGNED: Location information not available
  LAW:
    closestack: Closed Stacks - Ask At Desk
    web: Online Access
    media: Media
    micro: Microform
    open3: Open Stacks - 3
    open3a: Open Stacks - 3A
    open4: Open Stacks - 4
    open4a: Open Stacks - 4A
    open5: Open Stacks - 5
    open5a: Open Stacks - 5A
    open6a: Open Stacks - 6A
    govdoc: Open Stacks - 7
    oversize2: Closed Stacks - Ask At Desk
    oversize5a: Open Stacks - Oversize - 5A
    rarestacks: Remote
    reference: Reference
    reserve: Reserves
    serials: Journals
    archives: Archives - Ask At Desk
    trials: Special Collections - Ask At Desk
    hirst: Special Collections - Ask At Desk
    specintl: Special Collections - Ask At Desk
    pamphlets: Special Collections - Ask At Desk
    specpa: Special Collections - Ask At Desk
    rawle: Special Collections - Ask At Desk
    rawle3: Special Collections - Ask At Desk
    stacks: Stacks
    UNASSIGNED: Location information not available
  MAIN:
    ILL: Inter-Library Loan
    juvenile: Juvenile
    leisure: Leisure Reading
    m_reserve: Media Reserves
    reference: Reference
    reserve: Reserves
    serials: Journals
    servicedsk: Service Desk
    stacks: Stacks
    techserv: Technical Services
    govdocmicr: Government Doc Microforms
    govdoc: Government Documents
    govweb: Government Doc Web
    micro: Microform
    rarestacks: Remote
    UNASSIGNED: 'Problem: See Library Staff'
  PODIATRY:
    intref: Internal Reference
    leisure: Leisure Reading
    media: Media
    reference: Reference
    reserve: Reserves
    serials: Journals
    stacks: Stacks
    techserv: Technical Services
    UNASSIGNED: Location information not available
  PRESSER:
    presser: Learning Center
    plc: Listening Library
    UNASSIGNED: Location information not available
  KARDON:
    a_rare: Ambler
    b_rare: Blockson
    g_remote: Ginsburg
    l_remote: Law
    p_govdocmf: Government Documents
    p_GovDocs: Government Documents
    p_media: Media
    p_micro: Microform
    p_remote: Charles
    p_oversize: Charles
  ROME:
    exhibit: Exhibits
    fiction: Fiction
    media: Media
    oversize: Oversize Stacks
    reference: Reference
    reserve: Reserves
    serials: Journals
    stacks: Stacks
    UNASSIGNED: Location information not available
  SCRC:
    rarestacks: Reading Room
    UNASSIGNED: Location information not available
  KIOSK:
    kiosk: Kiosk
  RES_SHARE:
    OUT_RS_REQ: Interlibrary Loan
    IN_RS_REQ: Interlibrary Loan

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
