name: Update Airflow Variable

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  update_airflow_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add SSH key for Airflow
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AIRFLOW_DEPLOY_KEY }}

      - name: Install pipenv
        run: python -m pip install --upgrade pip pipenv

      - name: Install Airflow host SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AIRFLOW_HOST_SSH_KEY }}" > ~/.ssh/conan_the_deployer
          chmod 600 ~/.ssh/conan_the_deployer

      - name: Update Airflow variables
        run: bash .github/scripts/update-airflow.sh
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
