name: Workflow Failure Notify

permissions:
  contents: read

on:
  workflow_run:
    workflows: ["CI lint and test with Docker-Compose Solr", "Update Airflow Variable"]
    types: [completed]

jobs:
  notify_on_failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    uses: tulibraries/.github/.github/workflows/slack-notify.yml@main
    with:
      repo: ${{ github.event.workflow_run.repository.full_name }}
      run_id: ${{ github.event.workflow_run.id }}
      workflow: ${{ github.event.workflow_run.name }}
    secrets: inherit
